seek-oss/seek-style-guide

- app/components/Home/components/Body/components/Colors/components/ColorPalette/ColorPalette.js
- app/components/Home/components/Body/components/Colors/components/ColorPalette/ColorPalette.less
- theme/palette/accessible-variants.less
- theme/palette/elements.less
- theme/palette/grays.less
Makes the footer darker to add room for a gray panel that fits between our background colour and the footer colour. As a result of the darker colour we also need an accessible variant of our link blue.
Includes updates to the style guide app for layout of the Colour Palette preview.
> Darken footer and add accessible link colour

- react/index.js
Decided to clean up the exportation of components in the react folder:
- Removed the exported object and streamlined the `export` so that it's part of the` import`
- Break down exports into groups so that we can get a quick overview of what's actually available for consumption.
This is in preparation for a second PR that will add the Accessibility to components to the `style-guide`.
> Have tidied up the react folders exports

- react/Accessibility/ScreenReaderSkipLink.js
- react/Accessibility/ScreenReaderSkipLink.less
- react/Accessibility/ScreenReaderSkipTarget.js
- react/Accessibility/ScreenReaderSkipTarget.less
- react/index.js
Have included all the Accessibility from `chalice` so that it can be used across projects.
> Adding Accessibility exports

- react/index.js
Noticed while reimporting components into chalice
> Fixed erroneous export of ScreenReaderSkipTarget

- theme/type/type.less
I've verified with Scott that this is the only remaining place where the desired small-screen and large-screen type sizes should differ.  If we can get this in, we can call this our baseline, and discuss adjustments to it case by case going forward, rather than thrashing while trying to re-re-re-confirm our commitment to them as a whole.
As far as I know nobody is consuming these sizes.  This PR should unblock CR from using them (it currently uses Standard but not the others).  From this point on, deviation would be our fault :)
> Adds values for responsive types as verified by Scott

- app/components/App/components/Header/Header.js
- app/components/Dropdown/Dropdown.js
- react/fields/Dropdown/Dropdown.js
- react/fields/Dropdown/Dropdown.test.js
- react/fields/MonthPicker/NativeMonthPicker/NativeMonthPicker.js
- react/index.js
- webpack.gh-pages.server.config.js
this feature would enable the dropdown to display nested information.
optionProps supports hierarchy structure, here is one example of options:
```
const options = [
{
label: 'Really really long job title that is not gonna fit',
value: '3'
},
{
label: 'Major Cities',
value: [
{
label: 'Melbourne',
value: '3004'
},
{
label: 'Sydney',
value: '3002'
}
]
},
{
label: 'Balarat',
value: '3005'
}
]
```
> dropdown supports hierarchy

- react/fields/Textarea/Textarea.less
fixes in this PR:
- fix to avoid the count number being wrapped to a new line.
issue:
- add more space between the help text and the count, since given some specific resolution, the help text and count will be joined together.
issue:
> fix textarea help style

- app/components/App/components/Header/Header.less
We've added too many navigation items for the existing layout, causing it to wrap unexpectedly.
At some point we'll need a more holistic change to the documentation layout, but this at least gets us back to a non-broken state.
Preview:
> Fix documentation layout

- package.json
- react/index.js
I couldn't release the latest version of the style guide because of a linting error. Turns out we run ESLint before release but not as part of the test script, which is why it also wasn't being run in CI.
> Run ESLint during test script

- app/components/App/components/Footer/Footer.js
- package.json
The outdated URL seemed to be causing issues with the setup process for semantic-release.
> Update repo URL to ‘seek-oss’

- package.json
- webpack.dev.config.js
- webpack.static.render.config.js
We're still having issues with the base bath on GitHub Pages, so hopefully this fixes the issue. This change avoids playing around with defaulting environment variables, which might be hanging on to state between build steps, in favour of defaulting in the context of each webpack build.
> ci(gh-pages): Define default base path in webpack config

- react/AsidedLayout/AsidedLayout.js
- react/Card/Card.js
- react/PageBlock/PageBlock.js
- react/Secondary/Secondary.js
- react/Section/Section.js
- react/Strong/Strong.js
- react/Text/Text.js
Any extra props passed to presentation components were being ignored, forcing you to add redundant wrapper elements if you needed to add aria roles, data attributes etc.
> fix(components): Spread props on presentational components

- react/Button/Button.less
Fix for the following situation where the external layout forces the button text to wrap which should never be the case.
**Before:**
**After:**
It makes it a less broken experience, but our implementations should hopefully never hit up against this anyway.
> fix(button): Prevent wrapping of button text

- app/components/Playground/Playground.js
- react/Text/Text.js
This PR should clean up the implementation code around using the `Text` component by providing helper props that wire up sub-components internally:
**Before:**
```jsx
<Text><Secondary><Strong>My text</Strong></Secondary></Text>
```
**After:**
```jsx
<Text secondary strong>My text</Text>
```
Makes the application code much more readable
> feat(text): Add strong & secondary modifiers to Text component

- .travis.yml
The Travis CI build step for PRs originating from forks are currently unable to pass because they
don't have access to secure environment variables, causing the deployment step to fail. Deployment
of static previews for PRs is a useful part of our workflow, but not something that should prevent
contribution from those who don't currently have access to the main repo.
I'm issuing this PR from my own personal fork to ensure this logic works correctly.
> ci(deployment): Skip deployment step on fork builds

- webpack.static.client.config.js
Extract text plugin was spamming the output with: 
```
Child extract-text-webpack-plugin: 
+ 19 hidden modules
Child extract-text-webpack-plugin: 
+ 19 hidden modules
Child extract-text-webpack-plugin: 
+ 19 hidden modules
Child extract-text-webpack-plugin: 
+ 19 hidden modules
Child extract-text-webpack-plugin: 
+ 19 hidden modules
...
```
This fix suppresses those log reports. 
Reference: https://github.com/webpack-contrib/extract-text-webpack-plugin/issues/97
> ci(webpack): Remove extract text log spam from build output

- app/components/Playground/Playground.js
- react/Card/Card.js
- react/Card/Card.less
- react/Section/Section.js
- react/Section/Section.less
This PR is a proposal to introduce a `group` concept for layout components. When using a series of layout components that form a group, the current implementation adds a lot of unnecessary whitespace. Sometimes we want to visually separate a single `<Card>` or `<Section>` with minimum visual disruption. In the case of closely related cards, we add a single grey separator between them, and in the case of closely related sections, we only use 2 grid rows to separate them.
@tamoore I'd love your input on this, since this is primarily aimed to address the gaps you've raised.
> feat(layout): Add Card and Section groups

- package.json
This update to our commit flow now asks for breaking changes as a separate question, automatically
prefixing the response with the standard breaking change message prefix, instead of relying on
developers to provide this manually.
> chore(commitizen): Update cz-conventional-changelog to v2.0.0

- react/Header/Header.less
- react/Header/UserAccount/UserAccount.less
Responsively we drop off the employer site link, but we were leaving the divider behind.
Also noticed that the user name wasnt being truncated due to a class name not matching.
> fix(header): Fix username class & remove divider responsively

- react/Header/Navigation/Navigation.js
- react/Header/__snapshots__/Header.test.js.snap
A small oversight in the extraction of the `<Header />`, we accidentally made the "$150k Jobs" navigation item singular.
> fix(navigation): Pluralise 150k navigation label

- react/fields/MonthPicker/CustomMonthPicker/CustomMonthPicker.js
The `<MonthPicker>` component renders `<Dropdown>` components as children, but doesn't disable their messages, leading to multiple `<FieldMessage>` components stacking vertically. This produces extraneous whitespace between the fields and the month picker's message.
(☝️ How ironic...)
This change sits messages directly under the fields, as expected:
> fix(monthpicker): Fix stacked messages in MonthPicker

- react/Text/Text.js
This removes the nested span (while still retaining a central source of style) when using modifiers such as positive, critical, secondary, strong on Text as it was unexpected and not easy to modify the CSS of that inner span.
**Example**
Input before change:
`<Text positive className="foo">Hello</Text>`
Output before change:
`<div className="foo"><span>Hello</span></div>`
Input after change:
`<Text positive>Hello</Text>`
Output after change:
`<div className="foo">Hello</div>`
> feat(text): Removal of nested span in Text

- react/Header/Header.js
- react/Header/Header.test.js
- react/Header/__snapshots__/Header.test.js.snap
BREAKING CHANGE: Moved away from true/false/null for tri-state management of `authenticated` on the `<Header />`. Now uses explicit strings of `authenticated`/`unauthenticated`/`pending` being passed into `authenticationStatus`.
> feat(header): Use strings for authentication state

- react/fields/MonthPicker/NativeMonthPicker/NativeMonthPicker.less
There is an unnecessary `z-index: 2` on the month pickers chevron that is causing issues with elements that overlap the chevron.
This fixes a bug we are seeing in showcase for the new profile page:
> fix(monthpicker): Fix stacking order of native month picker chevron

- react/Dropdown/Dropdown.less
This PR changes the chevron color to black, based on talk with Dan, he thought the black chevron would make the dropdown appear actionable.
Plus, this PR would also fix a chevron issue on smaller screen if the label and dropdown list are going together. The reason is that on smaller screens, the font-size of the label would change to 18px from 14px on bigger screens. Removing the 'top' would fix this issue.
this is the chevron layout issue on small screen:
> fix(Dropdown): Change chevron color and alignment

- docs/components/Playground/Playground.js
- package.json
- webpack.static.render.config.js
Using the latest version of static-site-generator-webpack-plugin, we no longer need to manually maintain a list of paths to render. Instead, we can automatically crawl all relative links from the two entry points we have currently.
Once we formalise the playground into a pattern library, we won't even need to provide paths at all since all pages with be crawlable from the root path.
> docs(build): Render docs with static site crawler

- docs/components/Home/Preface/Preface.js
- docs/components/Playground/Playground.js
- docs/components/Playground/Playground.less
- react/Section/Section.js
- react/Section/Section.less
After some initial feedback, the whitespace-altering variants of the `Section` component are proving to be more confusing than anticipated, often providing either too much or too little whitespace.
As a result, we've decided to roll these back, opting for manual application-level styling in the short term. However, we'll continue a longer term focus on working with designers to figure out which whitespace rules we can standardise, but only after clear patterns have emerged across multiple applications.
BREAKING CHANGE: The "group" and "slim" props no longer have any effect on Section components
Remove slim sections:
```diff
-<Section slim>
+<Section className={styles.slim}>
+.slim {
+  padding-top: 0;
+  padding-bottom: 0;
+}
```
Remove section groups (note that you'll need to manually …
> feat(Section): Deprecate section groups and slim sections

- react/AsidedLayout/AsidedLayout.js
Need interface to be able to apply a class to the aside div, screenshot shows use case for where I need to add `align-self: flex-end;`.
> feat(AsidedLayout): Add interface for className for aside div

- scripts/deploy-gh-pages.js
The `basePath` in the deployment script was pointing at the old `dist` directory 😞
> docs(site): Fix GitHub Pages deployment

- config/autoprefixer.config.js
- docs/webpack.static.client.config.js
- webpack/index.js
We're currently relying on the default browser support policy of Autoprefixer, instead of defining our own, as we would typically do in an application context. The list in this PR is taken from our core search product, but further changes may be required.
> fix(styles): Provide browser list to Autoprefixer

- .npmignore
It is a copy of what was in .gitignore but swapped dist for docs so we can use https://github.com/seek-oss/seek-style-guide/pull/169.
> fix(dist): Add .npmignore so dist folder is published

- react/Text/Text.js
This fixes an issue raised by @mengtzu, seemingly caused when text modifier components like `<Strong>` are imported *before* usage of its equivalent inline modifier like `<Text strong>`.
An example of this issue can be seen below (note that the `Strong` styles are defined *before* the `Text` styles):
> fix(Text): Use nested span for modifiers to fix import order issues

- config/babel.config.js
- docs/webpack.dev.config.js
- docs/webpack.static.client.config.js
- docs/webpack.static.render.config.js
- package.json
- standalone/header-footer/webpack.config.js
- test/babel.transform.js
- webpack/index.js
Also refactored babel config into the 'config' folder, shared with webpack decorators.
I stumbled across this issue when I noticed that, seemingly since we fixed the minification step, our documentation now shows minified component names in many cases, e.g.
> fix(components): Automatically add displayName to React components

- react/PageBlock/PageBlock.less
This PR aligns the content area provided by `PageBlock` with the `Header`. The `Header` goes full width below `1025px` so `PageBlock` now follows suit removing width and gutters.
> fix(PageBlock): Align PageBlock content with header responsively

- package.json
- react/Autosuggest/Autosuggest.test.js
- react/Button/Button.test.js
- react/Checkbox/Checkbox.test.js
- react/Dropdown/Dropdown.test.js
- react/MonthPicker/CustomMonthPicker/CustomMonthPicker.test.js
- react/MonthPicker/MonthPicker.test.js
- react/MonthPicker/NativeMonthPicker/NativeMonthPicker.test.js
- react/Rating/Rating.test.js
- react/TextField/TextField.test.js
- react/TextLink/TextLink.test.js
- react/Textarea/Textarea.test.js
- react/private/FieldLabel/FieldLabel.test.js
- react/private/FieldMessage/FieldMessage.test.js
Were currently seeing a lot of warnings when running tests which is making it difficult to see when tests are failing.  This PR tidies up all those warnings
> refactor(Tests): Fix warnings for deprecated react test packages

- .pullapprove.yml
Implemented [PullApprove](https://about.pullapprove.com/) to automate our PR approval practices. There are heaps of config options, I think this is a good baseline to start with but maybe checkout the [docs](http://docs.pullapprove.com/) and we can discuss further.
> ci(config): Use PullApprove to automate PR approval practices

- package.json
With the previous version of Preact, it took two clicks to open the menu because the underlying checkbox wasn't being updated. This issue is resolved with the latest version of Preact.
> fix(Header): Fix standalone Header menu by upgrading Preact

- .pullapprove.yml
This option sounds great in theory, but causes a lot of friction. Every time you merge the latest changes into your PR branch, it invalidates all approvals. This forces everyone to re-approve if another PR is merged ahead of you.
> ci(PullApprove): Disable 'reset_on_push'

- .pullapprove.yml
Rather than checking for `WIP`, I figured a more important check is that it features the string `: ` at all. WIP commits don't include this string, so they'll still fail. I could have gone a lot further with the validation, but figured I'd keep it simple enough for this use case.
> ci(PullApprove): Validate PR titles

- .gitignore
- .npmignore
- .travis.yml
- scripts/git-to-sketch.js
- scripts/sketch-to-git.js
The idea is to enable design tooling to download the components' Sketch files, probably from [unpkg](https://unpkg.com) so that clients don't need to unpack tarballs from npm.
Since our design tools won't have any idea where to find all the Sketch files, we now generate a `sketch-manifest.json` file which lists all the relative paths for consumers to iterate over, which currently looks like this:
```json
{
"files": [
"react/Button/Button.sketch",
"react/Checkbox/Checkbox.sketch"
]
}
```
> feat(Sketch): Publish Sketch files to npm

- .pullapprove.yml
This should (hopefully) fix an issue where some PR approvals were being ignored. Besides, this also seems to make more sense—only those on the style guide team should be able to issue approvals anyway.
> ci(PullApprove): Assign style guide team to PullApprove reviewers list

- theme/palette/accessible-variants.less
sk-pink-on-gray-light is currently #d4006b which is not accessible on #E1E1E1. It's also not in the brand guidelines. 
Updating to #BD0B67 which is accessible across both greys
> fix(accessibility): sk-pink-on-gray-light

- react/private/FieldMessage/FieldMessage.less
This PR will resolve an issue for Dropdown, if the field message is set to empty on media screen.
Here is a summary of the current issue:
For now, The whole height of the dropdown with Help text as empty string, is set to 108.
but, if with the error message, the whole height is 117.
so, the fix here is to add extra 9px to the margin-bottom on media screen.
> fix(FieldMessage): adjust field message margin if it is empty set by Dropdown

- react/AsidedLayout/AsidedLayout.less
Luckily a release of this hadn't been triggered yet because it was a refactor. Picked this up by looking at the new page layout docs and noticing that the `<AsidedLayout>` demos were broken.
> fix(AsidedLayout): Fix AsidedLayout responsive mixin

- theme/mixins/type.less
Noticed this minor error while introducing stylelint. Not sure this is affecting anyone, since these mixins are considered legacy at this point and substandard type is a new addition to the hierarchy, but worth cleaning up in the meantime regardless.
> fix(type): Fix 'substandardText' mixin

- docs/src/components/PageLayout/PageLayout.js
- react/StyleGuideProvider/StyleGuideProvider.less
- react/Text/Text.demo.js
- react/Text/Text.js
- react/Text/Text.less
- theme/type/type.less
BREAKING CHANGE: Design review may be required.
This PR makes a few notable changes:
- Hero text is bumped up from light (300) to regular (400)
- Headline and heading text is bumped up from regular (400) to bold (600)
- `<Text>` now accepts a `light` prop if light text is still required, although this will be the exception going forwards.
- Base font colour of `<StyleGuideProvider>` is now set to `@sk-black`, which is #212121. Previously, no colour was set, which resulted in the browser default of #000000.
I also updated the page layout guide to use headings instead of headlines, since the new bolder headings now look great alongside `superstandard` type 🙌
> feat(Text): Make desktop headings bolder, enforce base font colour

- package.json
Duplicate devDependancy already included in dependancies (picked up by yarn, can we remove `yarn.lock` from the `.gitignore` yet?! 🙏 )
> build(devDependencies): remove duplicate devDependency

- react/SlideToggle/SlideToggle.less
The tick icon within the slide toggle is slight off centre.  Shifting it by a few pixels so it lines up nicely
> fix(SlideToggle): Fix tick icon alignment in slide toggle

- react/Header/Header.js
- react/Header/Header.less
- react/Header/Navigation/Navigation.less
- react/Header/__snapshots__/Header.test.js.snap
Refactored the `Header` to make gutters more consistent and cross browser compliant. We had some issues in IE11 at certain screen sizes and inconsistent gutters. This unifies the top banner and the logo/user banner to only have a half gutter spacing below the `grid-container-width`.
Tested across many browsers and looks good to me. The same `Header` you have always known now just more consistent with 11 less media queries 🎉
> fix(Header): fix overflow & consistent xbrowser gutters

- docs/server.js
Allows local dev server to be accessed from VM. This was required for me to test/dev against IE 11 recently. Thought it would be worth putting in a PR.
> build(devserver): Enable accessing dev server from VM

- README.md
We've somehow missed this until recently, but installing the style guide as a dev dependency can cause issues in server rendered applications when running `npm install --only=production`. This can lead to missing dependencies at runtime, which varies depending on the dependencies of your own application. As a result, we're now recommending that style guide consumers *always* install it as a regular dependency instead.
> docs(readme): Suggest installation as runtime dependency

- react/Autosuggest/Autosuggest.less
- theme/mixins/type.less
Currently user can't observe full suggestions list if it overflows the screen.
So as a user I should be able to still browse all options even if they overflow. 
This PR fixes it.
> fix(Autosuggest): Scroll through options on mobile if they overflow

- package.json
- standalone/header-footer/webpack.config.js
The mobile menu (in particular the latest change with scroll locking) wasn't correctly working when using the standalone version of the Header. After discussion with @markdalgleish we decided to switch back to using vanilla React even at the cost of file size (98kb vs 220kb).
> fix(Header): Switch out Preact for React (standalone components)

- react/Autosuggest/Autosuggest.js
Currently if user focuses on autosuggest field browser scrolls to the field.
However, when user selects a suggestion then scrolls a bit and then clears suggestions, browser won't scroll back to the field as field is still focused and this focus even is not called, which leads to incorrect behaviour in conjunction with scroll locking on mobile.
This is also the case when you select a suggestion, scroll and then trying to change suggestions again without blurring out of the field. Overlay will be shown, scroll lock will happen, however, browser won't scroll to the field.
This PR binds scrolling to the event when suggestions are shown instead of the focus event.
> fix(Autosuggest): Bind scrolling to suggestions shown event

- react/Autosuggest/Autosuggest.js
Current behaviour in Autosuggest is to lock scrolling on the page when suggestions list is presented and backdrop is shown.
This feature turned to be super buggy in mobile iOS Safari, so we will probably release without scroll-locking and then give it a go one more time.
Here are the issues we faced:
- Adding ScrollLock component prevents touch-scrolling inside the list when it overflows
- Attempt of re-enabling touch-scrolling inside the list (whilst body is locked) leads to the issue that when suggestions list ended and user is continuing scrolling (keeping finger inside the suggestions list) it scrolls the page itself
- Just setting body/wrapping component styles in many ways keeps being ignored by touch events
> feat(Autosuggest): Remove scroll locking feature from autosuggest

- react/Autosuggest/Autosuggest.js
Autosuggest now supports labelProps directly instead of via `inputProps.labelProps`
``` diff
- <Autosuggest {...} inputProps={ labelProps, ...inputProps } />
+ <Autosuggest {...} inputProps={ inputProps } labelProps={ labelProps } />
```
> feat(Autosuggest): move label prop to the root level of component

- theme/layout/z-indexes.less
- theme/mixins/backdrop.less
Due to multiple stacking elements there is a need in extra z-index inbetween 0 and inline-overlay, so  backdrop has been granted it's own higher z-index thus -inline-overlay could be used
> feat(Z-indexes): Add intervals between z-indexes, add separate z-index for backdrop

- .github/PULL_REQUEST_TEMPLATE.md
- CONTRIBUTING.md
This is totally up for discussion, but figured I'd get the ball rolling with a first pass.
We've had some issues with our automatically generated release notes being too sparse, particularly when it comes to breaking changes, and confusion for contributors around what level of detail is required to address this.
So, to help guide contributors, I've added a pull request template which will show up in the description box when opening a PR.
Let me know what you think. Keen to discuss this more, but hoping to at least get a good initial version in place.
> chore(GitHub): Add initial pull request template

- react/Autosuggest/__snapshots__/Autosuggest.test.js.snap
- react/Text/Text.js
- react/Text/Text.less
Have modified the Text component to, by default, use a span instead of a div for semantic reasons.
Block level elements aren't valid inside certain elements, e.g. a `<div>` inside an `<a>`
> fix(Text): Use a span tag for Text components instead of divs

- docs/src/components/Demo/Demo.js
- docs/src/components/PageLayout/PageLayout.js
- react/Autosuggest/Autosuggest.demo.js
- react/Checkbox/Checkbox.demo.js
- react/Dropdown/Dropdown.demo.js
- react/MonthPicker/MonthPicker.demo.js
- react/TextField/TextField.demo.js
- react/Textarea/Textarea.demo.js
The issue here was that we were creating a new component on every render (`<BoundComponent>`) so that we could bake in props ahead of time, but this was causing the component instance to be constantly destroyed and recreated. This meant that all state, both inside the component and in the DOM, wasn't being retained correctly.
To solve this, instead of binding the props to the component, we pass the props down to the `<Demo>` component and let it combine the props internally.
Fixes #276
> docs(site): Ensure demo components re-render correctly

- docs/src/components/App/Header/Header.js
- docs/src/components/App/Header/Header.less
- react/Button/Button.demo.js
- react/MonthPicker/MonthPicker.demo.js
- react/SlideToggle/SlideToggle.demo.js
- react/Text/Text.demo.js
- react/TextField/TextField.demo.js
This change is paving the way for more documentation by providing some basic structure to the IA. As part of this change, I've standardised the page titles and URLs for component demo pages to strictly match the name of the component (e.g. `Text` instead of `Typography`, especially since we're likely to write a high level guide to typography at some point)
> docs(site): Group nav items into 'Guides' and 'Components'

- docs/src/components/Demo/Code/Code.js
- package.json
- react/Text/Text.demo.js
Code samples are automatically generated, but this has led to a few quirks that make them differ from how you'd actually write the code in practice. To fix this, this commit makes the following changes:
- Replace all instances of `prop={true}` with `prop`, while leaving `prop={false}`, e.g. `<Text hero={true}>` becomes `<Text hero>`
- Hide any custom styling via the `style` prop, which is used purely for visual purposes on the style guide demo site, e.g. `<Section style={{ background: 'blue' }}>` becomes `<Section>`
- Detect and display *all* style guide components in import statements, not just the root component, e.g. `import { Card } from 'seek-style-guide/react'; <Card><Section>...` becomes `import { Card, Section } from 'seek-style-guide/react'; <Card><Section>...`
- Use multiline …
> docs(site): Tidy up generated code samples

- docs/src/Routes.js
- docs/src/components/App/Header/Header.js
- docs/src/components/Demo/Demo.js
- docs/src/components/Demo/Demo.less
- docs/src/components/PageLayout/PageLayout.js
- docs/src/components/Typography/Typography.js
Adding our 2nd ever guide to the documentation site, this time focused on typography. I also made some tweaks the the visual styling of our guide pages, which I also carried through to our page layout guide.
> docs(site): Add typography guide

- package.json
Upgrades Basekick to the latest v3.0.0 release.
Refining the Basekick module has resulted in `line-height` no longer needing to be expressed as a scale, rather as a pixel value that is the result of the type row span times the grid row height. This simplifies the output CSS to use pixels for `font-size` and `line-height` and only express the `transform` as a scale (in `em` units).
> fix(Text): Upgrade basekick to v3.0.0

- react/Hidden/Hidden.js
- react/Hidden/Hidden.test.js
- react/Hidden/__snapshots__/Hidden.test.js.snap
feat(Hidden): Add ability to pass down a component that will wrap children
RFC URL: None
Additional unnecessary markup should be avoided when using hidden, because it might lead to semantically incorrect markup such as li items wrapped in spans, etc.
EXAMPLE USAGE:
```js
<Hidden component='li'>foo</Hidden>
```
> feat(Hidden): Add ability to accept a component that will wrap children

- react/Header/SignInRegister/SignInRegister.js
- react/Header/UserAccountMenu/UserAccountMenu.js
- react/Header/__snapshots__/Header.test.js.snap
Prefix the `data-analytics` tag for sign in, register & sign out links in the header with `header:`
At the moment there is no way to distinguish between different sign in, register & sign out links on the page as they are all tracked as the same thing. The patten of `header:sign-in` follows all the other links in the header.
**While this shouldn't be a breaking change to anybody (hence not marked as one). I have found a issue in the way the homepage team has implemented sign in/register links which ill break. I'm working with them on this issue.**
> fix(Header): Update analytics data attr for sign in, register & sign out links

- standalone/header-footer/src/client.js
- standalone/header-footer/src/makeStandalone.js
Default the standalone `Header` to use `LogoRainbow`.
Currently no other way to do this, have discussed with @markdalgleish and this is temporary.
> fix(standalone): Default standalone header to rainbow logo

- docs/src/components/PageLayout/PageLayout.js
- docs/src/components/Playground/Playground.js
- react/CardGroup/CardGroup.js
- react/index.js
Added `CardGroup` component to support a more future proofed API for grouping components of the same type. `CardGroup` is just a implementation of `<Card group />` so at the time of writing this is a non breaking change.
RFC URL:
https://github.com/seek-oss/seek-style-guide/issues/321
While working on `ButtonGroup` it became evident the keeping the same interface, that being `<Card group/>` & `<Button group />` didn't make sense for the component `Button`.
MIGRATION GUIDE:
Before:
```js
<Card group>
<Card {...} />
<Card {...} />
</Card>
```
After:
```js
<CardGroup>
<Card {...} />
<Card {...} />
</CardGroup>
```
> feat(CardGroup): Add CardGroup

- react/Button/Button.less
Original:
Fixed:
When using multiple buttons in a group, it added an extra 2 vertical pixels, knocking it off grid.
> fix(ButtonGroup): Ensure grouped buttons align to grid

- react/ButtonGroup/ButtonGroup.demo.js
In the docs site, the ButtonGroup demo is left-aligned in the viewport, rather than sitting more centrally on large screens. To fix this, I've nested it within a PageBlock and Section combo, like it would be in a real product.
> docs(site): Render ButtonGroup demo in PageBlock

- react/Textarea/Textarea.demo.js
- react/Textarea/Textarea.js
- react/Textarea/Textarea.test.js
- react/private/FieldLabel/FieldLabel.js
Add description prop to Textarea for fields that require more explanation
RFC URL: https://github.com/seek-oss/seek-style-guide/issues/325
See [RFC](https://github.com/seek-oss/seek-style-guide/issues/325)
EXAMPLE USAGE:
```js
import {
Textarea
} from 'seek-style-guide/react';
<Textarea
description="Long description of highlights field"
id="highlights"
inputProps={{
onChange: () => {...},
value: '...'
}}
label="Highlights"
/>
```
> feat(Textarea): Add description prop to Textarea for longer explanations

- standalone/header-footer/src/client.js
Revert back to original seek logo from rainbow logo
Rainbow logo was a temporary change
> fix(standalone): Revert rainbow logo for standalone header

- react/Textarea/Textarea.demo.js
- react/private/FieldMessage/FieldMessage.demo.js
Some form element demos were starting to collect a few too many options, but some of them were either an edge case or completely redundant.
> docs(site): Clean up form element demos

- react/Logo/LogoIcon.js
- react/Logo/LogoText.js
- react/LogoRainbow/LogoRainbowIcon.js
- react/LogoRainbow/LogoRainbowText.js
Recent changes to React depreciated the use of PropTypes as a sub-package of React, suggesting the use of a dedicated prop-types dependency.
https://facebook.github.io/react/warnings/dont-call-proptypes.html
Builds using React 16 will no-longer fail to render in non-production builds.
Remove all uses of PropTypes as part of react package and use the dedicated prop-types package
React 16 no-longer provides prop-types directly. Using React 16 with Seek Style Guide may lead to errors when checking propTypes in development builds.
> fix(components): Use prop-types for PropType declarations

- docs/src/Router.js
- package.json
Upgrading React Router seems to have broken the docs on GitHub Pages, even though they work on Surge. It seems likely to be caused by deprecation of transparent base href tag support, but regardless of whether this is the actual cause of the issue or not, we now need to explicitly provide the basename to our history instance.
> docs(site): Configure router basename

- docs/webpack.static.client.config.js
- docs/webpack.static.render.config.js
- package.json
The client code now depends on the BASE_HREF environment variable, but it wasn’t provided within our webpack config, which meant that it resolved to ‘undefined’.
> docs(site): Provide ‘BASE_HREF’ env var to static build client

- docs/src/Router.js
I was accidentally using the v4 basename API, which doesn’t throw any errors but has no effect in v3.
> docs(site): Use history v3 basename API

- .github/ISSUE_TEMPLATE.md
- .github/PULL_REQUEST_TEMPLATE.md
- CONTRIBUTING.md
As discussed, trying to make the process of proposing changes and issuing pull requests a bit easier for consumers, without sacrificing the benefits of the existing approach.
> chore(github): Streamline RFC and PR templates

- README.md
Following the sample code, I had a compile error.
Adding this import should make it easier for new people to get started.
> docs(readme): Add missing StyleGuideProvider import in Setup code sample

- package.json
This gets all of our dependencies up to date. Some of our dependencies used caret version ranges while others didn't, so I figured it makes sense to standardise it. I opted for using carets to reduce churn on the style guide, especially since yarn is gaining in popularity, and later versions of npm produce a lockfile by default.
Since we're relaxing the version ranges of some dependencies, this is probably a good time to remind you that, if your app isn't using using yarn or an npm lockfile, it probably should.
> fix(deps): Upgrade dependencies, use caret version ranges

- react/Hidden/Hidden.less
Currently if Hidden is provided with a component that has it's own display styles, the component won't be hidden because component's styles are on top of the Hidden styles.
Here's an example:
```
<Hidden component={SomeComponent} />
.someComponentRoot {
display: flex;
}
```
This PR makes Hidden styles be more important then any display styling set on the component itself, so it actually not displayed when mobile/desktop prop is passed.
>  fix(Hidden): Make Hidden styles override component styles

- react/Columns/Columns.js
- react/Columns/Columns.less
- react/Columns/Columns.test.js
- react/Columns/__snapshots__/Columns.test.js.snap
At the moment the columns allow flexing based on content.
E.g Column 1 with wide content might be at 60% while Column 2 with thin content might be at 40%.
This may not be ideal default behavior.
From [MDN min-width](https://developer.mozilla.org/en-US/docs/Web/CSS/min-width)
> auto
> The default minimum width for flex items, providing a more reasonable default than 0 for other layouts.
This change will ensure column widths default to 1fr and do not change based on content.
Note: In both cases 'overflow-wrap: break-word;' is applied to the text
feat(Columns): Make Columns equal width by default
BREAKING CHANGE: Columns no-longer flexible by default.
MIGRATION GUIDE:
If you'd like to preserve the previous behaviour, use the new `flexible` prop.
Before:
```js
<Columns>
...
</Columns>
``` …
> feat(Columns): Make Columns equal width by default

- .travis.yml
Travis CI seems to hang on to stale packages due to our semver ranges.
This is an attempt to fix an issue with minified component code snippets on the docs site, which I can't reproduce locally. If it doesn't solve it, I'll close this PR.
> ci(travis): Disable Travis CI node modules cache

- docs/src/demoSpecs.js
- react/Card/Card.demo.js
- react/CardGroup/CardGroup.demo.js
These were a glaring omission, highlighted by a conversation I had today. We'll add the rest of the outstanding demos soon, but this is an important start.
Side note—the component list in the main navigation has finally crossed the line and become too long. I'll break it up into more digestible sections, but I'll leave this for a later PR.
> docs(site): Add Card and CardGroup demos

- package.json
Standalone header & footer has been broken since https://github.com/seek-oss/seek-style-guide/releases/tag/v31.0.0 as `seek-style-guide-webpack` didn't support cssSelectorPrefix until https://github.com/seek-oss/seek-style-guide-webpack/releases/tag/v2.1.0. This PR bumps the version of seek-style-guide-webpack to 2.1.0.
> fix(standalone): Update seek-style-guide-webpack package so css prefix works

- react/AsidedLayout/AsidedLayout.demo.js
- react/Columns/Columns.demo.js
Just adding a couple of glaring omissions from our component list.
Thanks to the previous change where we removed the need to maintain a centralised component demo list, all we have to do in this PR is add a couple of demo files! 🙌
> docs(site): Add AsidedLayout and Columns demos

- react/MonthPicker/CustomMonthPicker/CustomMonthPicker.js
- react/MonthPicker/CustomMonthPicker/CustomMonthPicker.test.js
- react/MonthPicker/CustomMonthPicker/getYearOptions.js
- react/MonthPicker/CustomMonthPicker/getYearOptions.test.js
- react/MonthPicker/MonthPicker.demo.js
- react/MonthPicker/MonthPicker.js
Add min & max year options to MonthPicker. Also, add sort order options (ascending/descending).
Currently, the `MonthPicker` has a static list of year options which is the current year going back 100 years. This PR makes the years configurable including which direction they are sorted. There are no breaking changes as the default props invoke the old behaviour. 
**Warning**: This change only affects the `CustomMonthPicker` which utilizes browser dropdowns. The `NativeMonthPicker` behaviour remains unchanged. Do not rely on these props for validation purposes as they do not ensure the data returned from the component in native mode. 
EXAMPLE USAGE:
```js
<MonthPicker
id="startMonth"
label="Start Month"
maxYear={2048}
minYear={2000}
ascendingYears={true} // default is false
/>
```
> feat(MonthPicker): Make year options configurable

- README.md
- theme/palette/elements.less
Adds (#f57c00) @sk-orange variable to the pallette color.
@sk-orange may become a replacement for current uses of @sk-yellow.
@sk-orange provides more contrast for smaller icons on light backgrounds than @sk-yellow.
> feat(Theme): Added new color sk-orange

- react/Footer/__snapshots__/Footer.test.js.snap
- react/Footer/data/company.js
New partner for SEEK Video Screen, Spark Hire, to be added into the Partner Services dropdown on our footer.
> fix(Footer): Add Spark Hire link to Partner Services

- react/Button/Button.demo.js
- react/Button/Button.js
- react/Button/Button.less
- react/Button/Button.test.js
- react/Button/__snapshots__/Button.test.js.snap
- react/ButtonGroup/__snapshots__/ButtonGroup.test.js.snap
This PR: 
- adds a non-required `ghost` prop to the Button
- adds styles to ghost blue buttons
- adds style to ghost white button
Example:
blue
transparrent white
Example usage:
```
<Button color="white" ghost {...restProps} />
```
>  feat(Button): Add ghost button styles

- react/Button/Button.js
- react/Button/Button.less
This PR:
- adds a non-required `ghost` prop to the Button
- adds ghost blue button styles
- adds ghost white button style
- if both transparent and ghost attributes applied, ghost gets ignored
- bug fix for button line height
- triggers unreleased changes from the previous PR for ghost buttons #377 
Example usage:
```
<Button color="white" ghost {...restProps} />
<Button color="blue" ghost {...restProps} />
```
> feat(Button): Add ghost buttons

- docs/src/components/SketchExports/SketchExports.js
Since Sketch libraries don't yet expose document colours, I figured it would be worthwhile to use the same workaround that we used for text styles.
In this PR, we're now exporting a `colours` symbol with the full colour palette available. This way, designers are able to drop the palette into their document and use the eyedropper tool to select the colours they need.
It's available in the library like any other symbol:
Once placed in the Sketch document, it looks like this:
> chore(sketch): Export colour palette as Sketch symbol

- .pullapprove.yml
- CONTRIBUTING.md
- package.json
This PR looks to tidy up a number of things around commit messages, hopefully reducing the chances of merging PRs with commit messages that do not conform/don't trigger a release.
Changes include:
- `validate-commit-msg` is deprecated in favour of `commitlint`
- Adopt conventional message format for linting to be consistent with commitizen setup.
- Update PullApprove to enforce PR titles conform with commit conventional format. This should reduce the chance of merge commits not having the correct message.
- Upgrade `stylelint` to [fix linting issue](https://github.com/stylelint/stylelint/issues/3042)
> chore(commitmsg): standardise on conventional commit message format

- docs/html-sketchapp.config.js
- package.json
This fixes an issue where our tests are failing on Travis CI due to browser sandbox issues:
```
Error: Failed to launch chrome!
[0111/021400.561758:FATAL:zygote_host_impl_linux.cc(126)] No usable sandbox! Update your kernel or see https://chromium.googlesource.com/chromium/src/+/master/docs/linux_suid_sandbox_development.md for more information on developing with the SUID sandbox. If you want to live dangerously and need an immediate workaround, you can try using --no-sandbox.
```
Since we're only running this tool against a style guide documentation page that is fully under our control, disabling the sandbox seemed like a reasonable workaround.
> ci(puppeteer): Fix Puppeteer sandbox issue on Travis CI

- react/Text/Text.js
Due to decorating while shallow render snapshots are getting `<DecoratedComponent />` rendered instead of `<Text />`
This PR fixes the issue.
> fix(Text): Add display name to Text component

- docs/src/components/Playground/Playground.js
- react/private/Icon/Icon.less
- react/private/withTextProps.js
```
<SomeIcon subheading /> or <SomeIcon size="subheading" />
```
was not styling icon correctly as per subheading size so size was fallbacking to default 16px.
PR fixes it.
Plus playground cleanup
> fix(Icon): Add missing subheading styles

- package.json
- react/Footer/__snapshots__/Footer.test.js.snap
- react/Footer/data/tools.js
- react/Header/Header.demo.js
- react/Header/Header.js
- react/Header/Navigation/Navigation.js
- react/Header/UserAccount/UserAccount.js
- react/Header/UserAccountMenu/UserAccountMenu.js
- react/Header/UserAccountMenu/UserAccountMenu.less
- react/Header/__snapshots__/Header.test.js.snap
- standalone/header-footer/src/render.js
This PR makes a few notable changes for AU:
- As the title says, rename "Advice & Tips" to "Career Advice"
- Move the "new" badge from "Profile" to "Career Advice"
- Show the Career Advice menu item on mobile, in the lower section
This PR also makes the following general changes:
- Generate a standalone header build of Career Advice
- Remove `react-scrollock` from the mobile menu, since the menu now requires scrolling on 320x480 phones
- Shrink the whitespace between menu groups on mobile
Note that, to ensure this isn't a breaking change, we still support "Advice & Tips" as a prop for `activeTab` and `newBadgeTab`, converting it to "Career Advice" on the way in.
> feat(Header): Rename ‘Advice & Tips’ to ‘Career Advice’ in AU

- react/Footer/__snapshots__/Footer.test.js.snap
- react/Footer/data/tools.js
- react/Header/UserAccountMenu/UserAccountMenu.js
- react/Header/__snapshots__/Header.test.js.snap
The myactivity page used to have a lot of content not related to saved
searches. To make navigation easier we linked the "Saved Searches" menu
item to the `#favourites` anchor just above saved searches.
Now that almost everything else has been removed from the page this just
awkwardly scrolls partially down the page. Fix by removing the
`#favourites` completely.
> fix(Header): Remove #favourite from myactivity

- theme/mixins/backdrop.less
In trying to debug a firefox issue in discover, we found that the
transparentBackgroup mixin really needed a lil refactor.
We are setting just top and left to 0 and then setting the width and height to
the viewport (minus 1 for an issue with firefox see the comments).
This then standardished, for discover at least the placement of the backdrops,
which have an altered stacking context. We can therefore adjust these with JS
for now until we get around updating the searchBar not to use transforms (if
possible).
This shouldn't impact other styleguide consumers, but if you do have an issue
whereby your stacking context changes it might be good to double check this does
not break your UI in subtle ways.
> fix(transparentBackdrop): Removing -999px left, top, right

- react/Section/Section.less
- theme/mixins/backdrop.less
Recent changes to the `<Section>` component introduced `overflow-x: hidden` to accomodate the pullout style for the `<Alert>` component. In IE, setting overflow-x creates a greyed out vertical scrollbar (screenshot below). 
Advertiser also has some issues with overflow being on `<Section>`
This problem is being fixed by removing overflow and adjusting the negative margin used in the pullout style to be exactly the same width as the gutter. This means overflow is not necessary because the pullout style no longer breaks out of a Section
> fix(Section): Fix overflow issues on Section components

- docs/src/client-render.js
- react/Alert/Alert.demo.js
- react/Alert/Alert.js
- react/Alert/Alert.less
- react/Alert/Alert.sketch.js
- react/Alert/__snapshots__/Alert.test.js.snap
If the provided message isn't long enough to wrap onto multiple lines, the close icon is no longer right aligned, instead being rendered immediately after the text:
I discovered this issue while creating Sketch symbols for the Alert component, which is why they're also included in this PR.
Also, while ensuring this fix also worked in IE11, I discovered a polyfill on the demo site, which I've also included in this PR.
> fix(Alert): Ensure close icon is right aligned

- README.md
- docs/src/components/Home/Hero/ButtonsPreview/ButtonsPreview.js
- docs/src/components/Home/Hero/ColorPreview/ColorPreview.js
- docs/src/components/Home/Hero/IconPreview/IconPreview.less
- react/Autosuggest/Autosuggest.demo.js
- react/Autosuggest/Autosuggest.less
- react/Button/Button.less
- react/SlideToggle/SlideToggle.less
- theme/palette/accessible-variants.less
- theme/palette/brand.less
- theme/palette/elements.less
- theme/palette/grays.less
This adds the following colours:
- `@sk-blue-darker`
- `@sk-blue-dark`
- `@sk-blue-light`
- `@sk-blue-lighter`
The new blues have been applied to links, buttons and form accents.
For accessibility reasons, `@sk-black` has also been darkened slightly.
While revisiting form elements, some visual styling has been tweaked:
- Button shadows are now inset, ensuring they match the button hue
- SlideToggle animations have been polished up a bit
> feat(theme): Add new blues and use internally, darken sk-black

- README.md
- react/Button/Button.less
- react/Header/NewBadge/NewBadge.less
- react/Header/UserAccountMenu/UserAccountMenu.less
Since [the introduction of the blue variants](https://github.com/seek-oss/seek-style-guide/pull/439), we can now more semantically reference shades of directly from the palette as opposed to using `sk-link` out of context of an actual link.
Also migrating away from using `sk-highlight` as this will be deprecated in the future in favour of using the palette or element colours specifically.
> chore(theme): Use palette blues rather than incorrect use of elements

- react/Columns/Columns.demo.js
- react/Columns/Columns.js
- react/Columns/Columns.less
- react/Columns/Columns.test.js
- react/Columns/__snapshots__/Columns.test.js.snap
New reverse prop allows consumers to flip the order of the children of the Columns component
When using the Columns component to replicate a fairly common UI pattern of Image on left with content on right, the pattern also offer the reverse of Content on left and Image on right.
Seeing as the Columns component does not accept a classNames prop to control this in the form of a CSS override, after discussing the problem with fellow contributors, the better option seemed to add a new prop that, if passed in, flips the ordering of the items within the columns component.
- added new `reverse` prop to Columns component
- updated existing styles to enable reversal of columns' children
- added unit test for reverse prop
- updated demo to include missing prop options with new prop option …
> feat(Columns): New reverse prop added

- README.md
Migrating away from [babel-plugin-transform-imports](https://www.npmjs.com/package/babel-plugin-transform-imports) in favour of [babel-plugin-seek-style-guide](https://github.com/seek-oss/babel-plugin-seek-style-guide).
> docs(readme): Add babel-plugin-seek-style-guide to readme

- .gitignore
- react/Autosuggest/__snapshots__/Autosuggest.test.js.snap
- react/Checkbox/Checkbox.less
When the checkbox text becomes too long for the space available it may attempt to wrap.
This causes the checkbox to shrink as it is a peer to the text content.
This change stops the checkbox 'box' area from shrinking or growing with the space available.
In addition this change will ensure the outer hit-box that handles the on-click will always encompass the text inside it, currently if text overflows it wont increase the hit-box.
> fix(Checkbox): Avoid shrinking checkbox in limited space

- react/Radio/Radio.less
Last minute changes on padding vs height broke the hidden input focus state which is used in osx voice over. This also makes more sense in that a hidden input does not need a top margin set.
> fix(Radio): Fix hidden input focus for VoiceOver

- react/Checkbox/Checkbox.less
Currently, when you untick the checkbox, the hover styles hang around until you blur it. This PR tweaks the styles so that the greyed-out tick is only visible on hover.
> fix(Checkbox): Remove grey tick from checkbox focus styles

- docs/webpack.dev.config.js
- react/Radio/Radio.less
Right now, in IE11, clicks on the radio button often fail. Turns out it's because the click event isn't bubbling up to the label correctly. This PR fixes it by disabling pointer events on all children of the label, ensuring that clicks are always registered against the label directly.
> fix(Radio): Fix dropped click events on elements inside label in IE11

- docs/src/components/Home/Hero/TextFieldPreview/TextFieldPreview.js
- react/Autosuggest/Autosuggest.js
- react/Autosuggest/Autosuggest.test.js
- react/Autosuggest/__snapshots__/Autosuggest.test.js.snap
- react/Checkbox/Checkbox.js
- react/Checkbox/Checkbox.test.js
- react/Checkbox/__snapshots__/Checkbox.test.js.snap
- react/Dropdown/Dropdown.js
- react/Dropdown/Dropdown.test.js
- react/MonthPicker/CustomMonthPicker/CustomMonthPicker.js
- react/MonthPicker/CustomMonthPicker/CustomMonthPicker.test.js
- react/MonthPicker/MonthPicker.js
- react/MonthPicker/MonthPicker.test.js
- react/MonthPicker/NativeMonthPicker/NativeMonthPicker.js
- react/MonthPicker/NativeMonthPicker/NativeMonthPicker.test.js
- react/Radio/Radio.js
- react/Radio/Radio.test.js
- react/Radio/__snapshots__/Radio.test.js.snap
- react/SlideToggle/SlideToggle.js
- react/SlideToggle/SlideToggle.test.js
- react/SlideToggle/__snapshots__/SlideToggle.test.js.snap
- react/TextField/TextField.js
- react/TextField/TextField.test.js
- react/TextField/__snapshots__/TextField.test.js.snap
- react/Textarea/Textarea.js
- react/Textarea/Textarea.test.js
- react/private/FieldLabel/FieldLabel.js
- react/private/FieldLabel/FieldLabel.test.js
BREAKING CHANGE:
`id` is now required as string for `Autosuggest`, `Checkbox`, `Dropdown`, `MonthPicker`, `TextField` and `Textarea` ( was already required for `Radio` & `SlideToggle`). 
This standardises our form elements, removes a custom prop type check, allow future accessibility fixes as well as making it not possible to accidentally opt out of these fixes by omitting a id.
> fix(FormElements): Make id string.isRequired for our form elements

- react/AsidedLayout/AsidedLayout.demo.js
- react/AsidedLayout/AsidedLayout.js
- react/AsidedLayout/AsidedLayout.less
We are looking to support layouts where an aside is provided to the left of the main content.
Support a left aside with the `position` prop.
Default behaviour remains right aligned.
Right aligned behaviour is unchanged.
'Reverse on mobile' behaviour is maintained for right and left aligned positions.
Currently the position of the aside node moves depending on the `reverse` prop.
CSS is then used to reverse the display order using `flex-direction: row-reversed` on desktop.
This change reuses this same functionality but applies XOR behaviour to `position` and `reverse` as follows.
Props | Desktop Position | Mobile Position | DOM Position
------ | ---------------- | --------------- | --------------
| `position=right` | Right | After | After |
| `position=right` `reverse` | Right | Before | …
> feat(AsidedLayout): Support left aligned aside

- docs/src/components/Typography/Typography.js
- react/Info/Info.demo.js
- react/Info/Info.js
- react/Info/Info.less
- react/Text/Text.demo.js
- react/Text/Text.js
- react/index.js
Inline with the other text short cut components such as `<Positive />` and `<Critical />` this adds `<Info />` also have added this as a prop to `<Text />`
EXAMPLE USAGE:
```js
This text is <Info>info</Info>
```
```js
This text is <Text info>info</Text>
```
> feat(Info): Add new component and prop for Text

- react/LightBulbIcon/LightBulbIcon.js
- react/LightBulbIcon/LightBulbIcon.svg
- react/index.js
Have added the ability to use a lightbulb icon in our suite of icons.
Current use case might be for something like:
> feat(LightBulbIcon): Addition of Lightbulb icon

- react/Rating/Rating.demo.js
- react/Rating/Rating.js
- react/Rating/Rating.test.js
- react/Rating/__snapshots__/Rating.test.js.snap
Currently if `description` prop is passed as a component it is coerced to string, which makes rendering incorrect.
> fix(Rating): Fix description component use case, add test

- react/Autosuggest/Autosuggest.demo.js
- react/Autosuggest/Autosuggest.js
- react/Autosuggest/Autosuggest.test.js
- react/Checkbox/Checkbox.demo.js
- react/Checkbox/Checkbox.js
- react/Checkbox/Checkbox.sketch.js
- react/Checkbox/Checkbox.test.js
- react/Checkbox/__snapshots__/Checkbox.test.js.snap
- react/Dropdown/Dropdown.demo.js
- react/Dropdown/Dropdown.js
- react/Dropdown/Dropdown.sketch.js
- react/Dropdown/Dropdown.test.js
- react/EmailField/EmailField.js
- react/MonthPicker/CustomMonthPicker/CustomMonthPicker.js
- react/Radio/Radio.demo.js
- react/Radio/Radio.js
- react/Radio/Radio.sketch.js
- react/Radio/Radio.test.js
- react/Radio/__snapshots__/Radio.test.js.snap
- react/TextField/TextField.demo.js
- react/TextField/TextField.js
- react/TextField/TextField.test.js
- react/TextField/__snapshots__/TextField.test.js.snap
- react/Textarea/Textarea.demo.js
- react/Textarea/Textarea.js
- react/Textarea/Textarea.sketch.js
- react/Textarea/Textarea.test.js
This non-breaking API change affects the following form components:
- **Autosuggest**
- **Checkbox**
- **Dropdown**
- **EmailField**
- **Radio**
- **TextField**
- **Textarea**
The following props can now be provided via the top-level component API, rather than via an `inputProps` object:
- **value**
- **checked** (for Checkbox and Radio)
- **type** (for Autosuggest and TextField)
- **onChange**
- **onFocus**
- **onBlur**
Currently, `value`, `checked`, `type`, `onChange`, `onFocus` and `onBlur` need to be provided via the `inputProps` object. Since these props are heavily used across all form fields, it adds a lot of friction to our component APIs. It also hinders our ability to create and use form libraries, since this is a custom, non-standard API.
**NOTE: Since `inputProps` is still …
> feat(forms): Add top-level value, checked, type, onChange/Focus/Blur

- react/Pill/Pill.less
Styling of the close button is broken in IE11 due to there being no support for `display:
inline-flex`. Using `display: flex` instead to work around the problem
> fix(Pill): Fix IE11 styling of close button

- package.json
As of [v0.5.2](https://github.com/seek-oss/html-sketchapp-cli/releases/tag/v0.5.2), html-sketchapp-cli no longer times out in CI waiting for the static server to start, so we can safely reenable this step.
> build(sketch): Re-enable html-sketchapp-cli in test script

- react/StyleGuideProvider/reset.less
The introduction of the `<Highlight>` component using the `<mark>` element has exposed that we previously had no reset for the default browser styles of this element — namely the `background-color` and `color`.
Anyone using the `<mark>` element elsewhere in their apps and expecting the default browser styling (extremely unlikely) will have to manually reinstate these rules.
> fix(reset): Remove browser default styling of mark elements

- react/Pill/Pill.demo.js
- react/Pill/Pill.js
- react/Pill/Pill.sketch.js
- react/Pill/Pill.test.js
- react/Pill/__snapshots__/Pill.test.js.snap
Pills currently only support rendering strings as content. In order to support the full range of typographical components, you can now render arbitrary nodes inside of pills.
To make this clearer, we now support rendering pill content as children. Note that, while this is a backwards compatible change, you're strongly encouraged to migrate to the new API.
EXAMPLE USAGE:
```js
<Pill>The last word is <Strong>strong.</Strong></Pill>
```
MIGRATION GUIDE:
```diff
-<Pill text="Hello world" />
+<Pill>Hello world</Pill>
```
> feat(Pill): Accept content as children, support all valid node types

- docs/src/components/Typography/Typography.js
- react/BulletList/BulletList.demo.js
- react/Rating/Rating.demo.js
- react/StarIcon/StarIcon.less
- react/Text/Text.demo.js
- react/Text/Text.less
- react/Text/Text.sketch.js
- react/Text/__snapshots__/Text.test.js.snap
- react/private/Icon/Icon.less
- react/private/__snapshots__/withTextProps.test.js.snap
- react/private/withTextProps.js
- theme/mixins/type.less
- theme/type/type.less
Details listed in issue https://github.com/seek-oss/seek-style-guide/issues/485
This change adds `large` Text size, exposing it to `<Text>` and all other components that uses `withTextProps`.
Large has a text size of 18 on both mobile and desktop, but in all other ways works as standard text.
EXAMPLE USAGE:
```js
<Text large>foo </Text>
```
> feat(Text): Add large body Text

- jest.config.json
- package.json
- react/Autosuggest/__snapshots__/Autosuggest.test.js.snap
- react/Footer/__snapshots__/Footer.test.js.snap
- react/Header/__snapshots__/Header.test.js.snap
- react/PartnerSites/Locales/__snapshots__/Locales.test.js.snap
- test/cssModules.transform.js
I split this PR out from another piece of work where I've started programatically iterating over the class names exported by a Less file. This clashes with our usage of `identity-obj-proxy` in unit tests, since `Object.keys` returns `[ ]` when called on a proxy object. Instead, we now have a custom Jest transformer that quickly extracts class names via a simple regex.
Not surprisingly, this change has highlighted differences in our snapshots where the proxy object didn't behave like a real CSS module.
> test(css): Parse CSS class names in unit tests

- react/Button/Button.less
Usage of 
```js
<Button
color="pink"
ghost
>
Hello world
</Button>
```
is now consistent with how blue and gray ghost buttons display.
> fix(Button): Fix how Button renders when pink and ghost

- react/Dropdown/Dropdown.demo.js
- react/Dropdown/Dropdown.less
BREAKING CHANGE:
`Dropdown` is currently not 100% to the parent at all times and therefore does not function the same as `TextField`. The issue is that the parent (.root) has `display: inline-block;` and the min-width is being dictated by the length of the `option`.
As a consumer if you where relying on inline-block you will have to add it but most use cases are fine.
> fix(Dropdown): Make Dropdown width 100% of parent

- react/Alert/__snapshots__/Alert.test.js.snap
- react/Autosuggest/Autosuggest.test.js
- react/Autosuggest/__snapshots__/Autosuggest.test.js.snap
- react/BulletList/__snapshots__/BulletList.test.js.snap
- react/Button/__snapshots__/Button.test.js.snap
- react/ButtonGroup/__snapshots__/ButtonGroup.test.js.snap
- react/Checkbox/__snapshots__/Checkbox.test.js.snap
- react/Columns/__snapshots__/Columns.test.js.snap
- react/Dropdown/Dropdown.test.js
- react/FieldLabel/FieldLabel.test.js
- react/FieldMessage/FieldMessage.test.js
- react/Footer/__snapshots__/Footer.test.js.snap
- react/Header/__snapshots__/Header.test.js.snap
- react/Hidden/__snapshots__/Hidden.test.js.snap
- react/MonthPicker/CustomMonthPicker/CustomMonthPicker.test.js
- react/MonthPicker/NativeMonthPicker/NativeMonthPicker.test.js
- react/PartnerSites/Locales/__snapshots__/Locales.test.js.snap
- react/PartnerSites/Sites/__snapshots__/Sites.test.js.snap
- react/Pill/__snapshots__/Pill.test.js.snap
- react/Radio/__snapshots__/Radio.test.js.snap
- react/Rating/__snapshots__/Rating.test.js.snap
- react/Section/__snapshots__/Section.test.js.snap
- react/SlideToggle/__snapshots__/SlideToggle.test.js.snap
- react/Text/__snapshots__/Text.test.js.snap
- react/TextField/TextField.test.js
- react/TextField/__snapshots__/TextField.test.js.snap
- react/TextLink/__snapshots__/TextLink.test.js.snap
- react/Textarea/Textarea.test.js
- test/cssModules.transform.js
This issue was discovered when trying to write tests for `Text.js` where it imported a `secondary` class from two different CSS modules.
As a bonus, I feel like this actually makes the snapshots easier to read since it makes it explicit where each class name is coming from.
> test(css): Prefix mock class names with file name to avoid conflicts

- jest.config.json
Travis builds are [failing](https://travis-ci.org/seek-oss/seek-style-guide/builds/408799649) due to [this issue](https://github.com/facebook/jest/issues/6766). The `testURL` config fixes it for me, let's see if it fixes the build!
> build(jest): Add testURL Jest config

- react/ReadMore/ReadMore.js
We need to fire a tracking event on jobapply when the candidate expands the job ad. This PR adds a new `onShowMore` prop which takes a function that will be executed as part of the `handleShowMore` handler, if it exists.
The `onShowMore` function is executed as part of `setState`s async callback, to ensure the state changes have been applied when it's called. The component will pass the new value of `this.state.showMore` into `onShowMore`, so that different events can be triggered for expand or collapse, or to make it can only trigger on either expand or collapse. 
EXAMPLE USAGE:
```js
const trackShowMore = detailIsExpanded => {
this.props.trackLink(detailIsExpanded ? 'job-details-expanded' : 'job-details-collapsed');
}
<ReadMore onShowMore={trackShowMore}>
<Text>Long piece of text</Text> …
```
> feat(ReadMore): Add 'onShowMore' event handler prop

- package.json
Yarn install was not de-duping the dependency correctly and still installing the incorrect version of react-autowhatever.
This is a non issue with npm and also will be removed when we rebuild Autosuggest.
> fix(Autosuggest): Add resolutions to fix yarn install for pinned package

- package.json
- react/Autosuggest/Autosuggest.js
- react/private/react-autosuggest/Autosuggest.js
- react/private/react-autosuggest/index.js
- react/private/react-autosuggest/theme.js
Switched to loading a internal version of `react-autosuggest@9.3.4`, the reason for this fork is to pin one of it’s dependencies `react-autowhatever` to a previous version `10.1.1` due to accessibility issues in the latest version. This was not possible via explicitly adding the wanted version of autowhatever as a dependency as there as issues getting this supported with both npm & yarn.
This should be temporary as our long term solution would be to build our own in house Autosuggest as currently there are still issues (but at least useable for now) with the current Autosuggest with certain screen readers.
> fix(Autosuggest): Fork react-autosuggest by copying code into style guide

- react/ReadMore/ReadMore.js
The change in #525 added a new prop to ReadMore and all flow checks passed in the styleguide. I'm using the ReadMore component in my app and my build of the latest styleguide version failed with the below error. I've adjusted the type to make `backgroundComponentName` a required prop. There's a default prop in place so there's no need to pass that prop when using the component
> fix(ReadMore): Make backgroundComponentName prop required

- react/Highlight/Highlight.demo.js
- react/Highlight/Highlight.js
- react/Highlight/Highlight.less
Demo: http://seek-style-guide--47c5bb50b08816738b4e10f5ad9159995d1098be.surge.sh/highlight
This PR https://github.com/seek-oss/seek-style-guide/pull/533 uses the concept of highlighting but doesn't directly use the highlight component because the required colour is not currently available. 
I've added the concept of tone to the highlight component to address the lack of colours currently available.
Neutral tone was added to the styleguide in this (currently un-merged) PR. https://github.com/seek-oss/seek-style-guide/pull/524. I'm planning to go back and do some refactoring here once this has been merged.
Before:
```js
<Highlight>My text</Highlight>
```
After:
```js
<Highlight tone={'neutral'|'positive'|'critical'|'info'}>My text</Highlight>
```
> feat(Highlight): Add the concept of tone to the highlight component

- react/Button/Button.js
The Button component currently passes a [ref](https://reactjs.org/docs/refs-and-the-dom.html) to it's child.
This ref is not used or accessible via typical use.
The ref was added as part of an attempt to [address border problems in Firefox](https://github.com/seek-oss/seek-style-guide/pull/30)
This no-longer appears to be necessary, see screenshot from Firefox with this change.
> fix(Button): Remove passing ref to child component

- react/Textarea/textAreaUtils.js
- react/Textarea/textAreaUtils.spec.js
This PR has two bug fixes in relation to this PR that was merged yesterday https://github.com/seek-oss/seek-style-guide/pull/533.
1. No key prop was set on the Highlight component.
2. Previously, the `formatInvalidText` function didn't return anything when highlighting a range with no end value AND when the text was shorter than the beginning of the range. In layman's terms, text highlighting is not appearing until a textarea is scrolled in cases where the start index requires scrolling to be seen.
> fix(Textarea): Update invalid text highlighting logic

- react/Badge/Badge.js
- react/Badge/Badge.test.js
- react/Badge/__snapshots__/Badge.test.js.snap
Currently internal classes will be overwritten with a className passed onto the badge.
```diff
<Badge className={styles.foo}>something</Badge> // will overwrite Badge styling
```
Also fixes console warning:
> fix(Badge): Prevent className overrides

- docs/server.js
- docs/webpack.dev.config.js
- package.json
Currently, seek-style-guide is running on port 3000, as is many other projects. Right now, the easiest way to run 2 projects simultaneously is to change the port temporarily on one of them.
This PR updates the style guide to check if port 3000 is open on `npm start`, and then increment to the next available port if it is busy.
> fix(webpack): Find an open port on start, if port busy

- react/Button/Button.less
Transparent buttons are supposed to follow our standard text typography.
Currently it increases the font-size to 18px due to the historical reasons when we had it baked into our responsive approach, which we've stopped doing.
Change has been introduced in the PR https://github.com/seek-oss/seek-style-guide/pull/158 and the potential risk (current bug) has been identified.
> fix(Button): Prevent font-size being increased on mobile

- react/TextField/TextField.js
The `tertiaryLabel` flow type of the `TextField` component was string, but this was not reflecting the use case. 
It is useful for consumers to be able to include a link (or potentially any other content) in this section. In the case of the Advertiser sign-in portal, we are including a forgot password link.
I have updated the `TextField` component flow type and also discovered that the prop type was missing in other components and included them in this PR as well.
* After discussion we are not including this change, the reason being:
> there was a consensus at the time to NOT include child component prop checks  in the parent component (like tertiaryLabel).
> fix: Change tertiaryLabel prop type to Object

- react/Highlight/Highlight.demo.js
- react/Highlight/Highlight.js
- react/Highlight/Highlight.test.js
- react/Highlight/__snapshots__/Highlight.test.js.snap
Due to the `[styles[tone]]: true` defaulting tone to `TONE.NEUTRAL`, by default we always get `undefined` class being assigned to the element.
This is caused by the fact that `.neutral` class does not exist in the stylesheet.
Tone is NOT a required prop from the consumer's perspective and also defaulting is a) doing nothing, b) introducing incorrect behaviour of the component.
> fix(Highlight): Fix undefined class being assigned to element

- docs/src/components/App/Header/Header.js
When adding the searchbar keyboard shortcuts, I broke the sandbox by removing the ability to type `/`. The event listener now checks that the event wasn't called on an `<input>` or `<textarea>` field when deciding whether to open the menu.
> fix(Header): Disable event listener on input fields

- react/Footer/Footer.js
- react/Footer/__snapshots__/Footer.test.js.snap
- react/Footer/data/tools.js
Added download links for iOS and Android into footer, and also fixed the Volunteering link on the NZ
site that was pointed to a non-SEEK url.
> fix(Footer): Add in new native app download links

- react/ToggleContent/ToggleContent.js
Fixes use case when `<ToggleContent />` is nested in a `<Form />`.
> fix(ToggleContent): Set type to 'button'

- react/Header/UserAccount/UserAccount.js
Given the `UserAccountMenu` is using a checkbox hack so it works without javascript, the behaviour should be an onChange handler on the checkbox rather than a click handler on the label. React was throwing an error as the checkbox had a `checked` prop without a corresponding `onChange`.
> fix(Header): Open UserAccountMenu onChange not onClick

- react/StyleGuideProvider/StyleGuideProvider.less
Addresses an issue with later versions of css-loader that can cause
```
Inconsistent rule global/local result in rule
```
The error can occur when some tags have `:global` and others do not.
> fix(StyleGuideProvider): Remove use of :global from html style

- react/TextField/TextField.less
The cursor in a TextField element has some funky behaviour in Safari
This is because the `touchableText` styles that get applied includes a `line-height` of 48px. Safari doesn't really know what to do with this, hence the issue.
This PR sets the line-height to `normal` for TextFields, fixing the cursor issue for Safari. I've tested clicking into the edges of the field in FF, Chrome, Safari, and IE, and they all support clicking right up to the edges still.
> fix(TextField): Set line-height to normal

- react/Header/UserAccountMenu/UserAccountMenu.js
- react/Header/__snapshots__/Header.test.js.snap
Add courses link in SKJ mobile site menu.
- Design: no icon below Employer Site
- Link to Seek Learning Course Directory site: https://www.seek.com.au/learning/
- `co.nz/learning` has been redirect to its au equivalent, so safe to just use `/learning` on both domain
BREAKING CHANGE: n/a
Design:
> feat(Header): Add courses link to mobile site

- react/ReadMore/ReadMore.js
There's currently no way to know if the more button is being displayed or not. I've got an analytics
requirement to find out if users are reading the text so am adding this prop to expose whether the
button is being displayed
> feat(ReadMore): Add ability to access state of more button visiblity

- react/Footer/__snapshots__/Footer.test.js.snap
- react/Footer/data/connect.js
More specific link so that logged in CS staff get the Help Centre instead of Zendesk admin dashboard.
> fix(Footer): Update help centre link

- react/Footer/Footer.js
- react/Footer/__snapshots__/Footer.test.js.snap
- react/Footer/data/company.js
Sidekicker links were requested to be updated to new format for SEO reasons.
Also the Partner Services menu toggle was hidden from NZ, and requested for it to be re-instated for the Sidekicker NZ link to be displayed.
> fix(Footer): Update Sidekicker links

- react/Header/UserAccountMenu/UserAccountMenu.js
- react/Header/UserAccountMenu/UserAccountMenu.less
- react/Header/__snapshots__/Header.test.js.snap
- Added (un-hide)`Recommended Jobs` link (to desktop).
- Remove the gray background behind Saved Search / Saved Jobs / Applied Jobs.
- Change on-hover colour to @sk-mid-gray-light.
- Add separator above Settings / Sign Out group.
The menu is wider now but saved / applied jobs will become saved & applied jobs (single item) in the future too.
>  feat(Header): Add Recommended Jobs to user account menu

- react/Header/UserAccountMenu/UserAccountMenu.js
- react/Header/UserAccountMenu/UserAccountMenu.less
- react/Header/__snapshots__/Header.test.js.snap
- theme/palette/elements.less
User Account Menu looks a bit strange containing most icons, but not the Applied Jobs icon.
We are adding an icon in with a colour value (`00b600`) that matches the Job Applied Success page's tick.
Also, after the addition of the Applied Jobs icon we have realised that this icon looks too similar in colour to the Recommended Jobs icon. 
We are changing the Recommended Jobs icon to `@sk-green` - the same colour as it is displayed on the dashboard panel.
> feat(Header): Add applied jobs icon (desktop)

- package.json
- react/Checkbox/Checkbox.demo.js
- react/Checkbox/Checkbox.demo.less
- react/Checkbox/Checkbox.js
- react/Checkbox/Checkbox.less
- react/Checkbox/__snapshots__/Checkbox.test.js.snap
BREAKING CHANGE: Requires consumers to have React v16.3+. Also introduces horizontal padding to the Checkbox in button mode to prevent label text colliding with button border.
Addresses the primary issue of supporting multiline labels as raised [here](https://github.com/seek-oss/seek-style-guide/pull/610). Also taking the opportunity to bring the `Checkbox` up to the standard of `Radio` in terms of screen reader outline by correctly positioning and sizing the hidden native input element.
Now takes a peer dependency on React v16.3+. Please ensure your app is compatible, see [the React v16 release](https://reactjs.org/blog/2017/09/26/react-v16.0.html) blog to see what is relevant for your app.
If using `<Checkbox type="button" />` please validate that the addition of the field gutter width …
> feat(Checkbox): Support multiline label and improved VoiceOver focus

- react/Checkbox/Checkbox.less
We lost the centre alignment for button checkboxes here https://github.com/seek-oss/seek-style-guide/pull/614/files#diff-7a3851b727f35854ccfee68663cc270bL100
> fix(Checkbox): Fix button checkbox centering

- docs/src/components/Demo/Demo.less
- react/Textarea/Textarea.demo.js
- react/Textarea/Textarea.js
- react/Textarea/Textarea.less
We require a `<Textarea />` with a height greater than 180px. While it is possible to override it using a CSS selector (something like .className textarea) it becomes extremely fragile when having highlighting enabled as it also inherits everything from `styles.textarea`.
> fix(Textarea): Remove max-height

- react/Footer/__snapshots__/Footer.test.js.snap
- react/Footer/data/employers.js
A new page promoting our Recruitment Software Partners has launched and needs to be surfaced in the candidate footer.
>  feat(Footer): Add RSP link to footer

- theme/type/type.less
We had incorrectly set `@sk-bold` to 600 (semi-bold) which is not available in our chosen font. As a result, the browser rounds the font weight up to 700 (bold). This is actually our desired font weight, so this wasn't technically an issue. The problem is that, when exporting to Sketch, this font weight gets rounded *down* to 500 (medium), causing a major discrepancy between our mock ups and the final medium.
For consumers, this doesn't actually change anything, so I'm marking this as a refactor.
> refactor: Use correct font weight for @sk-bold

- react/AccordionItem/AccordionItem.less
Added `position: relative;`, so that the `z-index` value on focus will take effect. Currently, the `box-shadow` used as an outline is being cropped when elements are directly below.
**Before:** 
**After**
> fix(AccordionItem): Make position relative to fix focus outline

- react/Pill/Pill.js
- react/Pill/__snapshots__/Pill.test.js.snap
Currently, when pills exist inside of a form, clicking on the close button will trigger a submit of the form. 
As I can't think of any scenario where closing a pill should trigger a submit, this PR changes the close buttons `type` to be `button`, rather than the default of `submit`.
> fix(Pill): Make close button a type of button

- react/Button/Button.less
- react/Button/Button.test.js
- react/Button/__snapshots__/Button.test.js.snap
Style guide demo page for button component displays an ugly variant for the white colour option (without "ghost" prop selected)
**After:**
NOTE: While a solid white button may not be part of the style guide (based on sketch example at bottom of page), at least this provides a nice looking fallback should the wrong prop options be provided.
> fix(Button): Add missing colour styles to white button option

- react/AccordionItem/AccordionItem.js
- react/AccordionItem/utils.js
This PR fixes:
- The content being set to the incorrect initialState
- Adds back the `height` being set to `auto` when the animation finishes. This accounts for content that could dynamically change size, such as textareas.
> fix(AccordionItem): Set height to auto

- react/Footer/__snapshots__/Footer.test.js.snap
- react/Footer/data/copyright.js
An experiment removing all sitemaps from the site is taking place and ensuring users are not able to click through to a non-existent page is the first step!
> fix(Footer): Remove sitemap from footer

- react/AccordionItem/AccordionItem.less
Have changed the Accordion text and chevron to be `@sk-black`, according to changes requested by Carmelia, after discussions with the broader UX team.
> fix(AccordionItem): Make text and link black

- react/Footer/__snapshots__/Footer.test.js.snap
- react/Footer/data/employers.js
The Marketing Insights blog has been 2 distinct content sites for a while now. A request has been made to split this link into separate URLs, same as the talent header already has.
> fix(Footer): Split marketing blog links

- react/Footer/__snapshots__/Footer.test.js.snap
- react/Footer/data/connect.js
- react/Footer/data/employers.js
The 'NEW' badge in the footer is changing away from 'SEEK Video', to the recently split Hirer blogs.
First time we've had 2 'NEW' badges, but its been approved and is ready to go live!
> fix(Footer): Move new badge to hirer blogs

- react/Footer/__snapshots__/Footer.test.js.snap
- react/Footer/data/tools.js
- This PR will be merged during a transition - Career Guide product will take `/career-advice` path
- Redirects will be in place - but it is important for SEO to internal products to point to new path
BREAKING CHANGE:
No breaking change
RFC URL:
no changes to API.
MIGRATION GUIDE:
not required
> fix(Footer): Update career guide url

- react/Header/UserAccountMenu/UserAccountMenu.js
- react/Header/__snapshots__/Header.test.js.snap
Adding a link to the settings page for the mobile menu dropdown, as currently the link exists only for desktop.
> feat: Add settings link on mobile

- react/Header/UserAccountMenu/UserAccountMenu.js
- react/Header/__snapshots__/Header.test.js.snap
I noticed this warning appearing after #657 was merged.
There's currently an `<li>` within an `<li>` that's triggering the warning. I've rejigged the jsx to produce valid html
> fix(Header): Fix validateDOMNesting warning for header li tags

- package.json
- react/StyleGuideProvider/StyleGuideProvider.js
The named export was added in `react-helmet` 5 and the default export was removed in `react-helmet` 6.
`react-helmet` 5 was released in 2017 so most people should already have matching versions.
BREAKING CHANGE: Requires `react-helmet` >= 5.0.0
> fix(deps): Support react-helmet 6.x

- react/ReadMore/ReadMore.less
The order of importance of the styles in the screenshot depends on the order of the styles in the css file. I'm making the `showMore` style more important than the base style of the `Text` component it's being applied to
> fix(ReadMore): Fix css order styling bug

- react/ToggleContent/ToggleContent.js
Fix warnings generated from rendering ToggleContent
> fix(ToggleContent): Fix invalid attribute warning
