seek-oss/seek-style-guide

- package.json
This is currently blocking the npm publish step.
> Remove private flag in package.json

- react/fields/Autosuggest/Autosuggest.test.js
- react/fields/TextField/TextField.js
- webpack.gh-pages.server.config.js
- Also add route for github pages.
> Allow mutliple ref assignment in textfield to fix autosuggest behaviour

- app/components/Autosuggest/Autosuggest.less
- app/components/Buttons/Buttons.less
- app/components/Code/Code.js
- app/components/Code/Code.less
- app/components/TextFields/TextFields.less
- app/components/Typography/Typography.less
- package.json
> Improved Code section formatting and added horizontal scrolling

- app/Routes.js
- app/components/App/App.js
- app/components/App/components/Header/Header.js
- app/components/SandboxPreview/SandboxPreview.less
- app/components/Textarea/Textarea.js
- app/components/Textarea/Textarea.less
- react/fields/Textarea/Textarea.js
- react/fields/Textarea/Textarea.less
- react/fields/Textarea/Textarea.test.js
- react/index.js
- webpack.gh-pages.server.config.js
Opening this to start the feedback process. 
Will update the demo and happy to update the API if it doesn't suit all purposes. 
Specifically interested in feedback from @dborysiewicz and @shawn-dsz.
Obviously Sir @mjt01 🎩  is included as well.
> Add textarea

- react/fields/Textarea/Textarea.js
- react/fields/Textarea/Textarea.test.js
> Make countFeedback prop for TextArea optional

- .travis.yml
- README.md
> Integrate with Travis CI

- .travis.yml
- README.md
- package.json
After this PR is merged, I'll follow up with a dummy patch release to make sure everything works.
closes #79
> ci(release): Use semantic-release

- README.md
This is just a single character readme change, but the commit message should trigger a patch release of `v15.1.1`.
> fix(test): Test semantic-release

- .travis.yml
- package.json
- scripts/deploy-gh-pages.sh
> ci(gh-pages): Automate GitHub Pages deployments

- app/components/App/App.js
- package.json
- webpack.dev.config.js
- webpack.static.render.config.js
Sorry, the last change didn't help, and I think I preferred the clarity of the original solution. I manually deployed earlier to fix the CSS issues, so I think the problem is that I'm not generating a diff, so no commit is added, so no deployment happens. I've changed the page title from "SEEK Styleguide" to "SEEK Style Guide", which I wanted to do anyway, so fingers crossed.
> ci(gh-pages): Test GitHub Pages deployment

- scripts/deploy-gh-pages.js
Deployments are still failing for some reason, but it's not reflected in the build logs. I realised I forgot to log deployment errors, so I've added some extra logging, but a refactor was required to ensure that all console logs are filtered.
> ci(gh-pages): Log GitHub Pages deployment errors

- app/components/TextFields/TextFields.js
Just testing the GitHub Pages deployment step.
> docs(textfield): Fix textfield label casing

- .eslintrc
- app/Routes.js
- app/components/App/App.js
- app/components/Playground/Atoms/IconButton/IconButton.js
- app/components/Playground/Atoms/IconButton/IconButton.less
- app/components/Playground/Atoms/Tab/Tab.js
- app/components/Playground/Atoms/Tab/Tab.less
- app/components/Playground/Atoms/TextLink/TextLink.js
- app/components/Playground/Atoms/TextLink/TextLink.less
- app/components/Playground/Playground.js
- app/components/Playground/Playground.less
- react/AsidedLayout/AsidedLayout.js
- react/AsidedLayout/AsidedLayout.less
- react/Card/Card.js
- react/Card/Card.less
- react/PageBlock/PageBlock.js
- react/PageBlock/PageBlock.less
- react/Secondary/Secondary.js
- react/Secondary/Secondary.less
- react/Section/Section.js
- react/Section/Section.less
- react/Strong/Strong.js
- react/Strong/Strong.less
- react/Text/Text.js
- react/Text/Text.less
- react/index.js
- theme/type/type.less
- webpack.static.render.config.js
Layout components:
- PageBlock
- Section
- AsidedLayout
- Card
Typographical components:
- Text
- Strong
- Secondary
These components are still experimental, so they are currently undocumented.
This also introduces the “playground” section of the style guide site as a dedicated space to experiment and collaborate on existing and upcoming components.
> feat(components): Add initial layout and typographical components

- CONTRIBUTING.md
- README.md
The contribution guide still needs to be fleshed out, but this is obviously an important first step.
> docs(readme): Add contributing guide, re-order readme

- react/fields/Checkbox/Checkbox.less
Checkbox was 25px instead of 27px (3 grid rows) because the calc was subtracting border widths
> fix(checkbox): Fix checkbox size

- react/fields/Checkbox/Checkbox.less
Fixed checkbox selected state background colour and tick colour so that they are in line with our
styles
> fix(Checkbox): Fix checkbox colours

- CONTRIBUTING.md
After working with @vedranio on a couple of pull requests, it became clear that our contribution docs needed a lot more work, particularly for those less familiar with the traditional workflow, so this is my first attempt at fleshing things out.
> docs(contributing): Improve contributing guide

- app/components/Playground/Playground.js
- app/components/Playground/Playground.less
- react/Columns/Columns.js
- react/Columns/Columns.less
- react/index.js
Note that this PR is more of a strawman proposal so that we can work together to get an initial version we're happy with. Keen to hear your thoughts.
> feat(columns): Add columns component

- README.md
- react/AsidedLayout/AsidedLayout.less
- react/Columns/Columns.less
- react/PageBlock/PageBlock.less
- theme/layout/breakpoints.less
- theme/type/responsiveType.less
- theme/type/type.less
BREAKING CHANGE: anyone consuming breakpoint externally will need to refactor
> refactor(*): refactors responsive breakpoint, removes large-screen mixin

- react/AsidedLayout/AsidedLayout.less
- react/Columns/Columns.less
- react/PageBlock/PageBlock.less
- theme/layout/breakpoints.less
- theme/type/responsiveType.less
add px to @responsive-breakpoint
remove unit() call from uses of @responsive-breakpoint
> refactor(less): add px to @responsive-breakpoint

- app/components/Buttons/Buttons.js
- react/Button/Button.js
- react/Button/Button.less
- react/Button/Button.test.js
Provide a "component" property to Button in order to pass in a custom html component name or a class reference.
> feat(button): Allow Buttons to be built on custom components

- react/TextField/ClearField/ClearField.js
- react/TextField/TextField.demo.js
The icon styles were adjusted via a class override, which causes rendering issues if the order of extracted CSS changes unexpectedly.
> fix(TextField): Fix TextField clear icon

- docs/src/demoSpecs.js
- react/Loader/Loader.demo.js
- react/Loader/Loader.js
- react/Loader/Loader.less
- react/index.js
Added the Loader component currently being used in Houston with a fade in animation.
> feat(Loader): Add Loader component

- react/Header/Header.demo.js
- react/Header/Header.js
- react/Header/Header.test.js
- react/Header/__snapshots__/Header.test.js.snap
If no user name is on authenticated account the Header will display the first part of the users
email address
> feat(Header): Display first part of user email if no username is present

- react/Textarea/Textarea.less
Pretty simple change, just up the font size to match the other text input components.
> fix(Textarea): Update font size to 18px to match other input components

- react/Footer/__snapshots__/Footer.test.js.snap
- react/Footer/data/connect.js
Product & Tech blog is about to be retired
> fix(Footer): Remove Product & Tech blog link

- react/Header/Header.less
Their might be a better way to do this by spending more time/adding extra html content but it's a very weird issue.
> fix(Header): Fix for IE11 flexbox horizontal centering

- docs/src/components/Demo/Demo.less
- docs/src/components/Home/Hero/Hero.less
- docs/src/components/Home/Hero/IconPreview/IconPreview.less
- docs/src/components/Playground/Playground.less
- react/AsidedLayout/AsidedLayout.less
- react/Autosuggest/Autosuggest.less
- react/Button/Button.less
- react/Checkbox/Checkbox.less
- react/Columns/Columns.less
- react/Section/Section.less
This PR will refine the media queries, to make it more descriptive, also consistent across the project.
> refactor(components): Consistently apply 'aboveSmallDevice' mixin

- react/Header/Header.less
Fixes the unexpected indentation of the logo and user account area in the banner on large devices. Also includes some specific media queries to keep the banner content from colliding with the edges of the window at certain resolutions.
> fix(Header): Fix gutters in Header for large devices

- package.json
- react/Autosuggest/Autosuggest.js
- react/Autosuggest/Autosuggest.less
Breaking changes in Misha's Autosuggest should not affect consumers of style-guide Autosuggest so it's not a breaking-change release https://github.com/moroshko/react-autosuggest/releases
> refactor(Autosuggest): Upgrade to latest version

- react/Autosuggest/Autosuggest.demo.js
- react/Autosuggest/Autosuggest.less
- theme/mixins/backdrop.less
https://github.com/seek-oss/seek-style-guide/issues/258
> fix(Autosuggest): Fix overlaying of autosuggest fields

- react/index.js
Sorted the exported groups in index.js alphabetically
Just feel it's a lil easier to find the component that you're looking for, or, to slot in a new one.
> refactor(index): Sort the exported groups in index.js alphabetically

- react/InfoIcon/InfoIcon.js
- react/InfoIcon/InfoIcon.svg
- react/index.js
> feat(InfoIcon): Addition of an info icon to the styleguide

- react/Header/Header.demo.js
- react/Header/Header.js
- react/Header/Header.test.js
- react/Header/__snapshots__/Header.test.js.snap
Support a `logoComponent` prop in the Header component, which accepts any valid React component.
This allows us to seasonally decorate the SEEK logo in the header.
EXAMPLE USAGE:
```js
const CustomLogo = () => { ... };
<Header {...} logoComponent={CustomLogo} />
```
Closes #310
> feat(Header): Allow custom logo overrides

- react/Header/Header.js
- react/Logo/Logo.js
- react/LogoRainbow/LogoRainbow.js
This message is irrelevant in New Zealand 🇳🇿
> fix(RainbowLogo): Only show rainbow logo in AU locale

- react/LogoRainbow/LogoRainbow.less
Patch release template
======================
fix(LogoRainbow): Fix typo in color definition for invert variant
Color defined is invalid
> fix(LogoRainbow): Fix typo in color definition for invert variant

- react/Footer/Footer.js
- react/Footer/__snapshots__/Footer.test.js.snap
- react/Footer/data/copyright.js
- react/Footer/data/employers.js
- react/Footer/data/tools.js
- react/Header/SignInRegister/SignInRegister.js
- react/Header/__snapshots__/Header.test.js.snap
No follow some header and footer links that has low seo values.
To save some search engine crawl budget by choosing to nofollow low value links
> fix(seo):  Nofollow specific Header and Footer links

- config/autoprefixer.config.js
- package.json
Standardising on our centralised browserslist config.
> chore(browserslist): Use browserslist-config-seek

- react/TextField/TextField.test.js
- react/TextField/__snapshots__/TextField.test.js.snap
No tests lost, cleanup, one step forward to deprecation of some dependencies
> test(TextField): Jestify and Enzymify TextField component tests

- .eslintrc
> style(eslint): Disable eslint-plugin-react's jsx-no-bind rule

- react/Header/Header.js
- react/Header/UserAccount/UserAccount.js
I need to know what the state of the menu is in the header. So I have added an option callback
function that could be called to allow us to know what it's current state is.
> feat(Header): Add menu toggle callback

- react/Button/Button.less
- theme/type/type.less
- Added @sk-medium font weight variable of 500
- Make all buttons (except transparent) to be medium weight
This (hopefully) makes solid blue buttons accessible (AA).
> feat(Button): Make button text medium weight, add @sk-medium

- react/Rating/Rating.less
Change as per new design.
Orange colour is accessible.
Before:
After:
> feat(Rating): Change Rating color to orange

- package.json
First usage of our new [shareable commitlint config](https://github.com/seek-oss/commitlint-config-seek) 🎉
> chore(commitlint): Use commitlint-config-seek

- react/Alert/Alert.js
- react/Alert/Alert.test.js
- react/Alert/__snapshots__/Alert.test.js.snap
After trying to use the Alert component in a project I found minor issues with it. Have made two small changes
- Allow the message to be a node. 
- Pass through additional props to the wrapping element of the alert
> fix(Alert): Alert component tweaks

- docs/src/components/Home/Hero/TextFieldPreview/TextFieldPreview.js
- react/Autosuggest/Autosuggest.js
- react/Autosuggest/Autosuggest.test.js
- react/Autosuggest/__snapshots__/Autosuggest.test.js.snap
- react/Checkbox/Checkbox.js
- react/Checkbox/Checkbox.test.js
- react/Checkbox/__snapshots__/Checkbox.test.js.snap
- react/Dropdown/Dropdown.js
- react/Dropdown/Dropdown.test.js
- react/MonthPicker/CustomMonthPicker/CustomMonthPicker.js
- react/MonthPicker/CustomMonthPicker/CustomMonthPicker.test.js
- react/MonthPicker/MonthPicker.js
- react/MonthPicker/MonthPicker.test.js
- react/MonthPicker/NativeMonthPicker/NativeMonthPicker.js
- react/MonthPicker/NativeMonthPicker/NativeMonthPicker.test.js
- react/Radio/Radio.js
- react/Radio/Radio.test.js
- react/Radio/__snapshots__/Radio.test.js.snap
- react/SlideToggle/SlideToggle.js
- react/SlideToggle/SlideToggle.test.js
- react/SlideToggle/__snapshots__/SlideToggle.test.js.snap
- react/TextField/TextField.js
- react/TextField/TextField.test.js
- react/TextField/__snapshots__/TextField.test.js.snap
- react/Textarea/Textarea.js
- react/Textarea/Textarea.test.js
- react/private/FieldLabel/FieldLabel.js
- react/private/FieldLabel/FieldLabel.test.js
This was incorrectly released as a patch instead of a breaking change.
Reverts seek-oss/seek-style-guide#460
> fix(FormElements): Revert #460

- package.json
This finally gets our symbols up to date and fixes all rendering issues! 🙌
> chore(sketch): Update html-sketchapp-cli to v0.4.1

- react/Section/Section.less
Intentionally decreasing desktop section gutter to 25px as a pre-work for creating a Gutter component and the breaking change to `@gutter-width` and `@column-width` variables.
> fix(Section): Decrease desktop section gutter to 25px

- react/Autosuggest/__snapshots__/Autosuggest.test.js.snap
This is breaking some of our open PRs, so fixing it as a separate PR.
> test(Autosuggest): Update Autosuggest snapshots

- react/ReadMore/ReadMore.demo.js
- react/ReadMore/ReadMore.js
- react/ReadMore/ReadMore.less
- react/index.js
- react/private/themeVars.js
- react/private/themeVars.json
The `ReadMore` component will truncate text if it is longer then the specified number of max lines of text. If it is equal or shorter it will render as normal. Currently, the component assumes your text is standard size. We could open up other sizes in future but opted to keep the component simple for now. 
EXAMPLE USAGE:
```js
<ReadMore maxLines={5}>
<Text>
{longText}
</Text>
</ReadMore>
```
> feat(ReadMore): Add 'ReadMore' component

- react/Alert/Alert.test.js
- react/Autosuggest/__snapshots__/Autosuggest.test.js.snap
Alert component was reporting an invalid prop type on one of it's test for passing in a boolean instead of a function.
> test(Alert): Update test with correct propType

- react/Footer/__snapshots__/Footer.test.js.snap
- react/Footer/data/company.js
New link for Certsy to be added to the Partner Services dropdown in the footer
> fix(Footer): Add Certsy link to Partner Services

- react/Footer/__snapshots__/Footer.test.js.snap
- react/Footer/data/tools.js
- react/Header/UserAccountMenu/UserAccountMenu.js
- react/Header/__snapshots__/Header.test.js.snap
- Update link in the header menu to link to the new management page
- Update footer in header menu to link to the new management page
- Stop hiding link on the mobile menu
> feat(SavedSearches): Update header and footer links to the new page

- react/Textarea/Textarea.demo.js
Updating labels within the textarea highlighting demo as they didn't correctly describe the highlighting functionality
> docs(Textarea): Update textarea highlighting demo

- package.json
- react/Badge/Badge.sketch.js
- react/BuildingIcon/BuildingIcon.sketch.js
- react/CheckMarkIcon/CheckMarkIcon.sketch.js
- react/ChevronIcon/ChevronIcon.sketch.js
- react/ClearIcon/ClearIcon.sketch.js
- react/CloseIcon/CloseIcon.sketch.js
- react/CriticalIcon/CriticalIcon.sketch.js
- react/CrossIcon/CrossIcon.sketch.js
- react/DeleteIcon/DeleteIcon.sketch.js
- react/DownRightArrowIcon/DownRightArrowIcon.sketch.js
- react/ErrorIcon/ErrorIcon.sketch.js
- react/FacebookIcon/FacebookIcon.sketch.js
- react/HeartIcon/HeartIcon.sketch.js
- react/HelpIcon/HelpIcon.sketch.js
- react/InfoIcon/InfoIcon.sketch.js
- react/LightBulbIcon/LightBulbIcon.sketch.js
- react/LinkedInIcon/LinkedInIcon.sketch.js
- react/MailIcon/MailIcon.sketch.js
- react/PlusIcon/PlusIcon.sketch.js
- react/ProfileIcon/ProfileIcon.sketch.js
- react/SearchIcon/SearchIcon.sketch.js
- react/StarIcon/StarIcon.sketch.js
- react/ThumbsUpIcon/ThumbsUpIcon.sketch.js
- react/TickCircleIcon/TickCircleIcon.sketch.js
- react/TickIcon/TickIcon.sketch.js
- react/TwitterIcon/TwitterIcon.sketch.js
- react/private/generateSketchIconSizes.js
> chore(sketch): Add Sketch symbols for icons and badges

- .travis.yml
- package.json
- scripts/post-commit-status.js
Now you don't have to remember our special URL format to see the preview site—it's included in the list of status checks within a PR.
> ci: Post Surge preview link to GitHub as commit status

- react/Section/Section.js
This PR wasn't quite right (https://github.com/seek-oss/seek-style-guide/pull/552), trying again
> fix(Section): Fix level and tone types

- .pullapprove.yml
Upgrade PullApprove and migrate to centralised config
> chore: Migrate PullApprove to v3

- react/ReadMore/ReadMore.demo.js
- react/ReadMore/ReadMore.demo.less
- react/TextField/TextField.js
- react/Textarea/Textarea.js
- react/private/attachRefs.js
This change allows refs to be passed through to the textarea element
> fix(Textarea): Pass ref through to textarea element

- react/Footer/__snapshots__/Footer.test.js.snap
- react/Footer/data/connect.js
Added link to the Footer for the new Help Centre product on Zendesk.
Updated name of the Contact Us link to remove the 'FAQ' portion as this has been made obsolete.
> feat(Footer): Add Help Centre link to Footer

- docs/src/components/App/Header/headerUtils.js
ESLint is now unhappy with the conditionals in header utils, because they contain constants.
I've declared the string literal as a const and replaced it in the conditions, which seems to have gotten the tests to pass.
> docs(headerUtils): Keep eslint happy about the headerUtils file

- react/Footer/__snapshots__/Footer.test.js.snap
- react/Footer/data/copyright.js
Privacy link has been requested to direct users to the new Privacy landing page (which links off to the privacy policy).
> fix(Footer): Update Privacy link

- package.json
- react/Button/Button.less
- react/ReadMore/ReadMore.js
- react/ReadMore/ReadMore.less
The `ghost` variant of the button component is the only one that has bold text. I'm reducing the font weight to` @sk-medium` to make it consistent with the other buttons.
I'm also changing the font weight of the `ReadMore` button to `@sk-medium` so it's consistent with other buttons and the `ToggleContent` component.
> fix(Bolding): Change Readmore and ghost button font weight

- react/AccordionItem/AccordionItem.js
This commit is to correct an incorrect commit message in https://github.com/seek-oss/seek-style-guide/pull/619. This PR is to get the Accordion published.
> feat(AccordionItem): Add AccordionItem

- react/Footer/__snapshots__/Footer.test.js.snap
- react/Footer/data/company.js
Removing link as SEEK has divested in Ximble
> fix(Footer): Removed Ximble link

- package.json
- react/private/withTextProps.js
Snyk has reported the following as a high severity security issue:
**Introduced through:** adv-shopfront-ui-sku@0.1.0 › seek-style-guide@40.2.0 › lodash@4.17.11
**Remediation:** Open PR to patch lodash@4.17.11.
**Overview**
lodash is a modern JavaScript utility library delivering modularity, performance, & extras.
Affected versions of this package are vulnerable to Prototype Pollution. The function defaultsDeep could be tricked into adding or modifying properties of Object.prototype using a constructor payload.
> fix: Update lodash to prevent security vulnerability

- react/Footer/__snapshots__/Footer.test.js.snap
- react/Footer/data/company.js
- react/Footer/data/connect.js
- react/Footer/data/employers.js
Updating a few links in the footer:
BrightMonday and Jobberman international partners
Helpcentre more specific link for SEO
Talent ContactUs new URL
> fix(Footer): Update footer links

- react/Footer/__snapshots__/Footer.test.js.snap
- react/Footer/data/connect.js
- react/Footer/data/tools.js
Added new footer link for our video.seek.com.au marketing portal
> Video footer link

- react/Footer/__snapshots__/Footer.test.js.snap
- react/Footer/data/connect.js
Adding the late-requested NZ URL for the new video portal
> fix(Footer): Add NZ videos footer link

- react/Footer/__snapshots__/Footer.test.js.snap
- react/Footer/data/tools.js
- react/Header/__snapshots__/Header.test.js.snap
Explore careers footer shall lead to `/career-advice/explore-careers
BREAKING CHANGE:
None
RFC URL:
None
> fix(Footer): Updated Explore Careers link

- react/Footer/__snapshots__/Footer.test.js.snap
- react/Footer/data/company.js
Adding a new partner link to the AU footer for GradConnection
> fix(Footer): Add GradConnection partner link

- react/Footer/__snapshots__/Footer.test.js.snap
- react/Footer/data/tools.js
Addition of a footer link to the new Recommended Jobs page
> fix(Footer): Add recommended jobs link

- react/Header/Header.demo.js
- react/Header/Header.js
- react/Header/Navigation/Navigation.js
- react/Header/__snapshots__/Header.test.js.snap
Decommission 150k jobs page
Ref: [AD-812]
> feat(Header): Decommission 150k tab
